### PR TITLE
fixed the stops from dierctions

### PR DESCRIPTION
**Pull request by KiqueDev**

### CODE REVIEW

**Comment by KiqueDev** [comment]
Still doesnt fix it.,..i will tkae a look morei nto this

**Comment by ef2k** [comment]
I was actually working on this too. Yeah thats not the complete fix.

**Comment by KiqueDev** [comment]
oh ok carry on then.... cu i though it was an easy fix lmk how it goes

**Comment by KiqueDev** [comment]
close

**Comment by ef2k** [comment]
Cool, please see https://github.com/brooklyndevs/metroly-html5/pull/70

**Pull request closed without merging**
